feat: search in dataserives
Informasjonsforvaltning/fdk-search-service pull request #34
Opened 2024-02-12 13:50 UTC by pooriamehregan

2024-02-12 19:11 UTC, NilsOveTen requested changes

2024-02-12 19:11 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/elastic/SearchRepositories.kt
>  interface DatasetSearchRepository : ElasticsearchRepository<Dataset, String>
```suggestion
@Repository
interface DatasetSearchRepository : ElasticsearchRepository<Dataset, String>
```

2024-02-12 19:11 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/elastic/SearchRepositories.kt
>  interface ConceptSearchRepository : ElasticsearchRepository<Concept, String>
```suggestion

@Repository
interface ConceptSearchRepository : ElasticsearchRepository<Concept, String>
```

2024-02-12 19:11 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/elastic/SearchRepositories.kt
> +interface DataserviceSearchRepository : ElasticsearchRepository<Dataservice, String>
```suggestion

@Repository
interface DataserviceSearchRepository : ElasticsearchRepository<Dataservice, String>
```

2024-02-13 11:08 UTC, terjesyl approved these changes

2024-02-14 12:51 UTC, terjesyl approved these changes

2024-02-14 14:14 UTC, NilsOveTen approved these changes

2024-02-20 09:53 UTC, merged