feat: add suggestion endpoints
Informasjonsforvaltning/fdk-search-service pull request #73
Opened 2024-02-20 07:47 UTC by hegeaal

2024-02-21 11:50 UTC, pooriamehregan approved these changes

2024-02-21 11:50 UTC, pooriamehregan commented on src/main/kotlin/no/digdir/fdk/searchservice/model/Suggestion.kt
> +
```suggestion
```

2024-02-21 11:50 UTC, pooriamehregan commented on src/main/kotlin/no/digdir/fdk/searchservice/service/SuggestionService.kt
> +
```suggestion
```

2024-02-21 11:50 UTC, pooriamehregan commented on src/main/kotlin/no/digdir/fdk/searchservice/service/SuggestionService.kt
> +        return builder.build()
```suggestion

        return builder.build()
```

2024-02-21 11:54 UTC, NilsOveTen commented on src/test/kotlin/no/digdir/fdk/searchservice/integration/SuggestionTest.kt
> +
```suggestion

```

2024-02-21 11:55 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/controller/SuggestionsController.kt
> +        return  ResponseEntity(suggestionService.suggestResources(query, null), HttpStatus.OK)
```suggestion
        return  ResponseEntity(
            suggestionService.suggestResources(query, null),
            HttpStatus.OK
        )
```

2024-02-21 11:56 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/controller/SuggestionsController.kt
> +    }
```suggestion
    ): ResponseEntity<List<Suggestion>> =
       ResponseEntity(
           suggestionService.suggestResources(query, null),
           HttpStatus.OK
       )
```

2024-02-21 11:57 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/controller/SuggestionsController.kt
> +    }
```suggestion
    ): ResponseEntity<List<Suggestion>> =
        ResponseEntity(
            suggestionService.suggestResources(query, searchType.pathVariableToSearchType()),
            HttpStatus.OK
        )
```

2024-02-21 11:57 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/controller/SuggestionsController.kt
> +}
```suggestion
}

```

2024-02-21 11:57 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/model/Suggestion.kt
> +)
```suggestion
)

```

2024-02-21 11:58 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/service/SuggestionService.kt
> +
```suggestion
```

2024-02-21 11:59 UTC, NilsOveTen commented on src/test/kotlin/no/digdir/fdk/searchservice/integration/SuggestionTest.kt
> +
```suggestion
}

```

2024-02-22 11:22 UTC, NilsOveTen approved these changes
men du har konflikter til main...

2024-02-22 14:34 UTC, NilsOveTen requested changes
fjern alle avro-filene, det har ikke noe med dette issuet å gjøre

2024-02-22 14:37 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/controller/SuggestionsController.kt
> +    private fun String.pathVariableToSearchType(): SearchType? =
flytt denne til `CommonMapper`

2024-02-23 06:08 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/controller/SuggestionsController.kt
> +    @GetMapping(value = ["/public_services_and_events"])
bare legg dette inn som et alternativ i toSearchType, og endre den til å returnere en liste

2024-02-23 09:09 UTC, merged