Feat/ha/add filter for relations
Informasjonsforvaltning/fdk-search-service pull request #82
Opened 2024-02-23 14:41 UTC by hegeaal

part of #69

2024-02-26 06:07 UTC, NilsOveTen requested changes

2024-02-26 06:07 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/model/CommonDataClasses.kt
> +data class Relation(
flytt eller kopier denne inn til SearchObject, for å tydeliggjøre at det bare er den som skal bruke den og endre type til å være enum

2024-02-26 06:07 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/model/CommonDataClasses.kt
> +  val type: String?
Lag en enum som samler alle relasjonene og bruk den i stedet for String

2024-02-26 06:07 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/model/CommonDataClasses.kt
> +@JsonInclude(JsonInclude.Include.NON_NULL)
```suggestion
```

2024-02-26 06:07 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/model/CommonDataClasses.kt
> +@JsonInclude(JsonInclude.Include.NON_NULL)
```suggestion
```

2024-02-26 06:07 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/model/CommonDataClasses.kt
> +@JsonInclude(JsonInclude.Include.NON_NULL)
```suggestion
```

2024-02-26 06:07 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/model/CommonDataClasses.kt
> +@JsonInclude(JsonInclude.Include.NON_NULL)
```suggestion
```

2024-02-26 06:07 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/model/CommonDataClasses.kt
> +@JsonIgnoreProperties(ignoreUnknown = true)
```suggestion
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
```

2024-02-26 06:07 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/model/CommonDataClasses.kt
> +@JsonInclude(JsonInclude.Include.NON_NULL)
```suggestion
```

2024-02-26 06:07 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/model/CommonDataClasses.kt
> +@JsonInclude(JsonInclude.Include.NON_NULL)
```suggestion
```

2024-02-26 06:07 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/model/CommonDataClasses.kt
> +@JsonInclude(JsonInclude.Include.NON_NULL)
```suggestion
```

2024-02-26 06:07 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/model/CommonDataClasses.kt
> +@JsonInclude(JsonInclude.Include.NON_NULL)
```suggestion
```

2024-02-26 07:16 UTC, hegeaal commented on src/main/kotlin/no/digdir/fdk/searchservice/mapper/ConceptMapper.kt
> +        relations.add(Relation(uri = it.isPartOf, type = "partitiveRelation"))
Ja, så begge skal legges til?

2024-02-26 07:20 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/mapper/ConceptMapper.kt
> +        relations.add(Relation(uri = it.isPartOf, type = "partitiveRelation"))
Hvis de ikke er null, ja

2024-02-27 12:51 UTC, pooriamehregan commented on src/main/kotlin/no/digdir/fdk/searchservice/mapper/DatasetMapper.kt
> +        "http://purl.org/dc/terms/relation" -> RelationType.relation
```suggestion
    val basePath = "http://purl.org/dc/terms";
    return when (referenceType?.uri) {
        "$basePath/source" -> RelationType.source
        "$basePath/hasVersion" -> RelationType.hasVersion
        "$basePath/isVersionOf" -> RelationType.isVersionOf
        "$basePath/isPartOf" -> RelationType.isPartOf
        "$basePath/hasPart" -> RelationType.hasPart
        "$basePath/references" -> RelationType.references
        "$basePath/isReferencedBy" -> RelationType.isReferencedBy
        "$basePath/replaces" -> RelationType.replaces
        "$basePath/isReplacedBy" -> RelationType.isReplacedBy
        "$basePath/requires" -> RelationType.requires
        "$basePath/isRequiredBy" -> RelationType.isRequiredBy
        "$basePath/relation" -> RelationType.relation
```

2024-02-27 14:05 UTC, NilsOveTen requested changes

2024-02-27 14:05 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/model/SearchObject.kt
> +    genericRelation,
```suggestion
    generalizes,
    specializes,
```

2024-02-27 14:05 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/model/SearchObject.kt
> +    partitiveRelation,
```suggestion
```

2024-02-27 14:05 UTC, NilsOveTen commented on src/test/kotlin/no/digdir/fdk/searchservice/integration/FilterTest.kt
> +                    Assertions.assertTrue(relation.uri == TEST_DATASET_FILTERS.uri)
Denne vil feile hvis vi legger til en relasjon på samme datasett som ikke peker på dette datasettet

2024-02-27 14:10 UTC, NilsOveTen commented on src/test/kotlin/no/digdir/fdk/searchservice/integration/FilterTest.kt
> +                    Assertions.assertTrue(relation.uri == TEST_DATASET_FILTERS.uri)
ikke 100% på at dette fungerer, men noe ala dette
```suggestion
                Assertions.assertTrue(searchObject.relations?.map { it.uri }.any { it.uri == TEST_DATASET_FILTERS.uri)
```

2024-02-27 14:24 UTC, hegeaal commented on src/test/kotlin/no/digdir/fdk/searchservice/integration/FilterTest.kt
> +                    Assertions.assertTrue(relation.uri == TEST_DATASET_FILTERS.uri)
Så ikke denne, så prøvde meg på dette:

```
val validValues = result.all { searchObject ->
                searchObject.relations?.any { relation ->
                    relation.uri == TEST_DATASET_FILTERS.uri
                } ?: false
            }
```

2024-02-27 14:32 UTC, NilsOveTen commented on src/test/kotlin/no/digdir/fdk/searchservice/integration/FilterTest.kt
> +                    Assertions.assertTrue(relation.uri == TEST_DATASET_FILTERS.uri)
👍 skal funke det

2024-02-28 08:14 UTC, NilsOveTen requested changes

2024-02-28 08:14 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/model/Dataset.kt
> +    val inSeries: List<InSeries>?,
```suggestion
    val inSeries: InSeries?,
```

2024-02-28 08:14 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/model/CommonDataClasses.kt
> +)
```suggestion
@JsonIgnoreProperties(ignoreUnknown = true)
data class Reference(
  val referenceType: ReferenceDataCode?,
  val source: SkosConcept?
)

@JsonIgnoreProperties(ignoreUnknown = true)
data class ObjectWithURI(
  val uri: String?
)
```

2024-02-28 08:14 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/model/DataService.kt
> +    val conformsTo: List<ConformsTo>?,
```suggestion
    val conformsTo: List<ObjectWithURI>?,
```

2024-02-28 08:14 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/model/Dataset.kt
> +    val conformsTo: List<ConformsTo>?,
```suggestion
    val conformsTo: List<ObjectWithURI>?,
```

2024-02-28 08:14 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/model/Dataset.kt
> +    val inSeries: List<InSeries>?,
```suggestion
    val inSeries: List<ObjectWithURI>?,
```

2024-02-28 08:14 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/model/Dataset.kt
> +    val informationModel: List<SkosConcept>?,
```suggestion
    val informationModel: List<ObjectWithURI>?,
```

2024-02-28 08:14 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/model/Dataset.kt
> +    val subject: List<Subject>?
```suggestion
    val subject: List<ObjectWithURI>?
```

2024-02-28 08:14 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/model/Service.kt
> +    val isClassifiedBy: List<SkosConcept>?,
```suggestion
    val isClassifiedBy: List<ObjectWithURI>?,
```

2024-02-28 08:14 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/model/Service.kt
> +    val isDescribedAt: List<SkosConcept>?,
```suggestion
    val isDescribedAt: List<ObjectWithURI>?,
```

2024-02-28 08:14 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/model/Service.kt
> +    val subject: List<SkosConcept>?
```suggestion
    val subject: List<ObjectWithURI>?
```

2024-02-28 08:14 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/mapper/EventMapper.kt
> +    }
```suggestion
```

2024-02-28 08:14 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/mapper/ServiceMapper.kt
> +private fun Service.getRelations(): List<Relation> {
mangler ikke requires?

2024-02-28 08:14 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/model/Service.kt
> +    val relation: List<Service>?,
```suggestion
    val relation: List<ObjectWithURI>?,
```

2024-02-28 08:14 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/model/Service.kt
> +    val requires: List<Service>?,
```suggestion
    val requires: List<ObjectWithURI>?,
```

2024-02-28 08:57 UTC, NilsOveTen reviewed
lag noen enhetstester for mapping av relasjoner for alle ressurstypene

2024-02-28 14:19 UTC, NilsOveTen commented on src/test/kotlin/no/digdir/fdk/searchservice/data/DatasetTestData.kt
> +        Reference(referenceType = ReferenceDataCode(code = null, prefLabel = null, uri = null), source = (ObjectWithURI(uri = "references_uri")))
Tydeliggjør mer hvilke som er hva i testen
```suggestion
    references = listOf(
        Reference(referenceType = ReferenceDataCode(code = null, prefLabel = null, uri = "$basePath/source"), source = (ObjectWithURI(uri = "source_uri"))),
        Reference(referenceType = ReferenceDataCode(code = null, prefLabel = null, uri = "$basePath/hasVersion"), source = (ObjectWithURI(uri = "has_version_uri"))),
        Reference(referenceType = ReferenceDataCode(code = null, prefLabel = null, uri = "$basePath/isVersionOf"), source = (ObjectWithURI(uri = "is_version_of_uri"))),
        Reference(referenceType = ReferenceDataCode(code = null, prefLabel = null, uri = "$basePath/isPartOf"), source = (ObjectWithURI(uri = "is_part_of_uri"))),
        Reference(referenceType = ReferenceDataCode(code = null, prefLabel = null, uri = "$basePath/hasPart"), source = (ObjectWithURI(uri = "has_part_uri"))),
        Reference(referenceType = ReferenceDataCode(code = null, prefLabel = null, uri = "$basePath/references"), source = (ObjectWithURI(uri = "references_uri"))),
        Reference(referenceType = ReferenceDataCode(code = null, prefLabel = null, uri = "$basePath/isReferencedBy"), source = (ObjectWithURI(uri = "is_referenced_by_uri"))),
        Reference(referenceType = ReferenceDataCode(code = null, prefLabel = null, uri = "$basePath/replaces"), source = (ObjectWithURI(uri = "replaces_uri"))),
        Reference(referenceType = ReferenceDataCode(code = null, prefLabel = null, uri = "$basePath/isReplacedBy"), source = (ObjectWithURI(uri = "is_replaced_by_uri"))),
        Reference(referenceType = ReferenceDataCode(code = null, prefLabel = null, uri = "$basePath/requires"), source = (ObjectWithURI(uri = "requires_uri"))),
        Reference(referenceType = ReferenceDataCode(code = null, prefLabel = null, uri = "$basePath/isRequiredBy"), source = (ObjectWithURI(uri = "is_required_by_uri"))),
        Reference(referenceType = ReferenceDataCode(code = null, prefLabel = null, uri = "$basePath/relation"), source = (ObjectWithURI(uri = "relation_uri"))),
        Reference(referenceType = ReferenceDataCode(code = null, prefLabel = null, uri = null), source = (ObjectWithURI(uri = "missing_type_uri")))
```

2024-02-29 06:34 UTC, NilsOveTen approved these changes

2024-02-29 07:11 UTC, merged