feat: add pagination
Informasjonsforvaltning/fdk-search-service pull request #90
Opened 2024-02-28 16:38 UTC by pooriamehregan

resolves https://github.com/Informasjonsforvaltning/fdk-search-service/issues/84

2024-02-29 13:44 UTC, hegeaal approved these changes

2024-02-29 13:52 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/fdk/searchservice/service/SearchService.kt
> +            }
```suggestion
        map { it.content }
          .toList()
          .let {
            SearchResult(
              hits = it,
              page = PageMeta(
                currentPage = pagination.getPage(),
                size = it.size,
                totalElements = this.totalHits,
                totalPages = ceil(totalHits.toDouble() / pagination.getSize()).roundToLong()
              )
            )
          }
```

2024-02-29 13:54 UTC, NilsOveTen requested changes
Legg til noen tester som viser at det er mulig å endre størrelsen på hver page og at du kan hente mer enn bare første side

2024-03-05 15:33 UTC, NilsOveTen approved these changes

2024-03-05 15:37 UTC, merged